Collapsables
CarsonWebster/RecipeWizard pull request #32
Opened 2023-06-14 11:34 UTC by troyschultz-ucsc

allow users to add a photo of a recipe they have cooked onto their favorites cards   by a direct image url entry from the user.

2023-06-14 21:34 UTC, CarsonWebster requested changes, later dismissed
I'm not sure this is quite functional yet. Let's see if we can rework the parts where I left comments. 

Until we get image or URL uploading to the database from the front end, let's refrain from merging to main

2023-06-14 21:34 UTC, CarsonWebster commented on .DS_Store
No need to push .DS_Store. I thought this was in the .gitignore?

2023-06-14 21:34 UTC, CarsonWebster commented on controllers.py
> +    imageUrl = request.json.get("imageUrl")
Should we really need to pass an imageUrl through the url when we call togglePin? Idk if this is the best solution to updating the imageUrl? Where does this url come from? Modifying the recipes image shouldn't be paired with pinning functionality

2023-06-14 21:34 UTC, CarsonWebster commented on controllers.py
> +            recipe.update_record(imageUrl=recipe.imageUrl)
What's going on here? Of the pinned recipe rows, are we getting the existing imageUrl, adding it to recipe in local recipe_dict variable, and updating the recipe in the db with that same Url? 

This seems redundant and we should't be updating db rows every time it's queried

2023-06-14 21:51 UTC, troyschultz-ucsc commented
> I'm not sure this is quite functional yet. Let's see if we can rework the parts where I left comments.
> 
> Until we get image or URL uploading to the database from the front end, let's refrain from merging to main

Thank you for reviewing my code. I appreciate your feedback. I understand that there are some comments that need to be addressed. If you have a moment, could you kindly assist me with the specific points you mentioned? I worked on this code all night, and I'm feeling a bit drained at the moment. While it may not be perfect, this version is at least functional and allows users to hyperlink their own images instead of storing the image files on the server. I would be grateful for your assistance in resolving the remaining issues. Thank you for your understanding and support.

2023-06-15 01:05 UTC, CarsonWebster commented
Refactored the image URL structure :)

2023-06-15 01:06 UTC, CarsonWebster approved these changes
Approve now can I fix merge conflicts?

2023-06-15 02:14 UTC, merged